Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/Cellar/python@3.9/3.9.13/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import matplotlib.pyplot as plt

def plot_vector2d(vector2d, origin=[0, 0], **options):
    return plt.arrow(origin[0], origin[1], vector2d[0], vector2d[1],
              head_width=0.05, head_length=0.1, length_includes_head=True,
              **options)


def puissiter(A,v0,lam,niter,epsilon):
    v = v0
    vv=[v0]
    l = np.dot(v0,np.dot(A,v0))
    ll = [l]
    k=0
    while np.fabs(lam-l)>epsilon and k<niter:
        w = np.dot(A,v)
        v = w/np.linalg.norm(w)
        l = np.dot(v,np.dot(A,v))
        vv.append(v)
        ll.append(l)
        k=k+1
    return ll, vv,k

A = np.array([[2.,1,-1],[1,3,1],[-1,1,4]])
lam =np.max(np.linalg.eigvals(A))
print("La plus grande valeur propre de A est ",lam)

epsilon = 1e-4
niter=50
ll, vv,k = puissiter(A,np.ones(3),lam,niter,epsilon)

plt.figure(figsize=(10,5))
plt.subplot(121)
plt.plot(range(len(ll)),ll,'-o',label='Puissances it√©r√©es')
plt.plot(range(len(ll)),lam*np.ones((len(ll)), dtype=np.uint8) ,'r')
plt.ylabel('valeur propre')
plt.xlabel('Iteration');
plt.text(0, lam+0.3, "$\lambda$", color="r", fontsize=18)
plt.legend()
plt.title("Valeur propre approch√©e √† "+ str(epsilon)+" pr√®s en "+str(k)+" it√©rations")

plt.subplot(122)
plot_vector2d(vv[0], color="b", linestyle="dotted")
plt.text(vv[0][0],vv[0][1],'v0')
plot_vector2d(vv[k-1], color="r", linestyle="dotted")
plt.text(vv[k-1][0],vv[k_1][1],'vfinal')

plt.title("Vecteur propre approch√©")
plt.tight_layout()



------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [1][0m, in [0;36m<module>[0;34m[0m
[1;32m     45[0m plt[38;5;241m.[39mtext(vv[[38;5;241m0[39m][[38;5;241m0[39m],vv[[38;5;241m0[39m][[38;5;241m1[39m],[38;5;124m'[39m[38;5;124mv0[39m[38;5;124m'[39m)
[1;32m     46[0m plot_vector2d(vv[k[38;5;241m-[39m[38;5;241m1[39m], color[38;5;241m=[39m[38;5;124m"[39m[38;5;124mr[39m[38;5;124m"[39m, linestyle[38;5;241m=[39m[38;5;124m"[39m[38;5;124mdotted[39m[38;5;124m"[39m)
[0;32m---> 47[0m plt[38;5;241m.[39mtext(vv[k[38;5;241m-[39m[38;5;241m1[39m][[38;5;241m0[39m],vv[[43mk_1[49m][[38;5;241m1[39m],[38;5;124m'[39m[38;5;124mvfinal[39m[38;5;124m'[39m)
[1;32m     49[0m plt[38;5;241m.[39mtitle([38;5;124m"[39m[38;5;124mVecteur propre approch√©[39m[38;5;124m"[39m)
[1;32m     50[0m plt[38;5;241m.[39mtight_layout()

[0;31mNameError[0m: name 'k_1' is not defined
NameError: name 'k_1' is not defined

